// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Model.Migrations
{
    [DbContext(typeof(ContextProject))]
    [Migration("20241205193602_AddAutoIncrementToCapteur")]
    partial class AddAutoIncrementToCapteur
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Model.DataModel.Capteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Dt_Modif")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<double?>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Capteur");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dt_Modif = new DateTime(2024, 12, 5, 19, 36, 1, 537, DateTimeKind.Utc).AddTicks(9454),
                            Name = "Capteur 01",
                            Type = "Type01",
                            Value = 22.5
                        },
                        new
                        {
                            Id = 2,
                            Dt_Modif = new DateTime(2024, 12, 5, 19, 36, 1, 538, DateTimeKind.Utc).AddTicks(56),
                            Name = "Capteur 02",
                            Type = "Type02",
                            Value = 55.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
